import 'dart:async';
import 'dart:io' show Platform;

import 'package:flame_audio/flame_audio.dart';
import 'package:flutter/foundation.dart';

/// Every sound effect in the game. Files live in `assets/audio/` and are
/// generated by `tools/audio/make_audio.py`.
enum Sfx {
  bombPlace,
  bombPlaceOther,
  explode,
  explodeFar,
  pickup,
  death,
  revive,
  ping,
  stageClear,
  gameOver,
  exitAngry,
  kick,
  freeze,
  uiTap,
  bossHit,
  ghost,
}

/// Small audio facade over flame_audio. Every call is fire-and-forget safe:
/// plugin errors are caught and logged, so audio can never crash the game.
class GameAudio {
  static final GameAudio instance = GameAudio();

  /// Off in widget tests and on platforms without audio; every call is then a
  /// no-op.
  static bool enabled = !_underTest;

  // `flutter test` sets this; there is no audio device there.
  static final bool _underTest =
      !kIsWeb && Platform.environment.containsKey('FLUTTER_TEST');

  double musicVolume = 0.6;
  double sfxVolume = 0.8;

  /// File name (relative to `assets/audio/`) of a sound effect.
  static String sfxFile(Sfx s) => '${_snake(s.name)}.wav';

  /// File name of the music loop for [world] (1..5, clamped; 0 = menu).
  static String musicFile(int world, {bool hurry = false}) {
    if (world <= 0) return 'music_menu.wav';
    final w = world.clamp(1, 5);
    return hurry ? 'music_w${w}_fast.wav' : 'music_w$w.wav';
  }

  /// Simultaneous voices per effect; frequent effects get more.
  static int _voices(Sfx s) => switch (s) {
    Sfx.explode || Sfx.explodeFar => 6,
    Sfx.bombPlace || Sfx.bombPlaceOther || Sfx.pickup || Sfx.uiTap => 3,
    _ => 2,
  };

  final Map<Sfx, AudioPool> _pools = {};
  final Map<Sfx, Future<AudioPool?>> _loading = {};
  String? _currentMusic;
  bool _bgmReady = false;

  /// Caches all SFX (and creates their player pools).
  Future<void> preload() async {
    if (!enabled) return;
    try {
      await FlameAudio.audioCache.loadAll(Sfx.values.map(sfxFile).toList());
    } catch (e) {
      debugPrint('GameAudio: preload failed: $e');
    }
    await Future.wait(Sfx.values.map(_pool));
  }

  Future<AudioPool?> _pool(Sfx s) {
    final ready = _pools[s];
    if (ready != null) return Future.value(ready);
    return _loading[s] ??= () async {
      try {
        final pool = await FlameAudio.createPool(
          sfxFile(s),
          maxPlayers: _voices(s),
        );
        _pools[s] = pool;
        return pool;
      } catch (e) {
        debugPrint('GameAudio: could not create pool for $s: $e');
        _loading.remove(s);
        return null;
      }
    }();
  }

  /// Plays a sound effect. Fire-and-forget; never throws.
  void play(Sfx s) {
    if (!enabled || sfxVolume <= 0) return;
    unawaited(_play(s));
  }

  Future<void> _play(Sfx s) async {
    try {
      final pool = await _pool(s);
      await pool?.start(volume: sfxVolume.clamp(0.0, 1.0));
    } catch (e) {
      debugPrint('GameAudio: play $s failed: $e');
    }
  }

  /// Loops the music for [world] (0 = menu). [hurry] picks the faster
  /// variant used in the last 30 seconds. Does nothing if that exact track is
  /// already playing.
  Future<void> playMusic(int world, {bool hurry = false}) async {
    if (!enabled) return;
    final file = musicFile(world, hurry: hurry);
    if (file == _currentMusic) return;
    _currentMusic = file;
    try {
      if (!_bgmReady) {
        _bgmReady = true;
        await FlameAudio.bgm.initialize();
      }
      await FlameAudio.bgm.play(file, volume: musicVolume.clamp(0.0, 1.0));
    } catch (e) {
      debugPrint('GameAudio: playMusic $file failed: $e');
      if (_currentMusic == file) _currentMusic = null;
    }
  }

  Future<void> stopMusic() async {
    if (!enabled) return;
    _currentMusic = null;
    try {
      await FlameAudio.bgm.stop();
    } catch (e) {
      debugPrint('GameAudio: stopMusic failed: $e');
    }
  }

  /// Updates volumes; a playing music track changes immediately.
  void setVolumes({double? music, double? sfx}) {
    if (music != null) musicVolume = music.clamp(0.0, 1.0);
    if (sfx != null) sfxVolume = sfx.clamp(0.0, 1.0);
    if (!enabled || music == null || _currentMusic == null) return;
    unawaited(() async {
      try {
        await FlameAudio.bgm.audioPlayer.setVolume(musicVolume);
      } catch (e) {
        debugPrint('GameAudio: setVolume failed: $e');
      }
    }());
  }

  static String _snake(String camel) =>
      camel.replaceAllMapped(RegExp('[A-Z]'), (m) => '_${m[0]!.toLowerCase()}');
}
